jobs:
  create-docker-images:
    machine: true
    steps:
      - checkout
      # Build 
      - run: docker build -f Dockerfile.ws . -t uncommon2022/ws
      - run: docker build -f Dockerfile.web . -t uncommon2022/web
      - run: docker tag uncommon2022/ws eu.gcr.io/uncommon2022/ws
      - run: docker tag uncommon2022/web eu.gcr.io/uncommon2022/web
      - run:
          name: "Is it built?"
          command: echo $GCP_PROJECT_KEY
      - run: docker images

      - run:
          name:  Google Cloud Authentication
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV

      - gcp-cloud-run/init
      - gcp-gcr/push-image:
          google-project-id: uncommon2022
          registry-url: "eu.gcr.io"
          image: eu.gcr.io/uncommon2022/web

      - gcp-gcr/push-image:
          google-project-id: uncommon2022
          registry-url: "eu.gcr.io"
          image: eu.gcr.io/uncommon2022/web

      - gcp-cloud-run/deploy:
          image: 'eu.gcr.io/uncommon2022/web'
          region: europe-west6
          service-name: web
          unauthenticated: true

      - gcp-cloud-run/deploy:
          image: 'eu.gcr.io/uncommon2022/ws'
          region: europe-west6
          service-name: ws
          unauthenticated: true

version: 2.1
orbs: 
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
  gcp-gcr: circleci/gcp-gcr@0.6.1
workflows:
  docker-workflow:
    jobs:
      - create-docker-images:
        context: cloud-test-auth