version: 2.1
jobs:
  create-docker-image:
    machine: true
    steps:
      - checkout
      # Build 
      - run: docker build -f Dockerfile.ws . -t uncommon2022/ws
      - run: docker tag uncommon2022/ws eu.gcr.io/uncommon2022/ws
      - run:
          name: "Is it built?"
          command: "echo Docker built"
      - run: docker images
      
workflows:
  say-hello-workflow:
    jobs:
      - create-docker-image