version: 2.1
jobs:
  create-docker-images:
    machine: true
    steps:
      - checkout
      # Build 
      - run: docker build -f Dockerfile.ws . -t uncommon2022/ws
      - run: docker build -f Dockerfile.web . -t uncommon2022/web
      - run: docker tag uncommon2022/ws eu.gcr.io/uncommon2022/ws
      - run: docker tag uncommon2022/web eu.gcr.io/uncommon2022/web
      - run:
          name: "Is it built?"
          command: "echo Docker built"
      - run: docker images
  deploy:
    docker:
      - image: google/cloud-sdk
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "eu.gcr.io"
          image: $IMAGE_NAME
      - cloudrun/deploy:
          platform: "managed"
          image: "eu.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME"
          service-name: "orb-gcp-cloud-run"
          region: $GOOGLE_COMPUTE_ZONE
          unauthenticated: true
workflows:
  docker-workflow:
    jobs:
      - create-docker-images
      - deploy