version: 2.1
jobs:
  create-docker-images:
    machine: true
    steps:
      - checkout
      # Build 
      - run: docker build -f Dockerfile.ws . -t uncommon2022/ws
      - run: docker build -f Dockerfile.web . -t uncommon2022/web
      - run: docker tag uncommon2022/ws eu.gcr.io/uncommon2022/ws
      - run: docker tag uncommon2022/web eu.gcr.io/uncommon2022/web
      - run:
          name: "Is it built?"
          command: "echo Docker built"
      - run: docker images

      - cloudrun/init
      - cloudrun/deploy:
          image: 'eu.gcr.io/uncommon2022/web'
          region: europe-west6
          service-name: web
          unauthenticated: true

      - cloudrun/deploy:
          image: 'eu.gcr.io/uncommon2022/ws'
          region: europe-west6
          service-name: ws
          unauthenticated: true
workflows:
  docker-workflow:
    jobs:
      - create-docker-images